# Generated by Django 2.0.5 on 2020-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('social_media', models.TextField(max_length=500)),
                ('summary', models.TextField(max_length=200)),
                ('skills', models.TextField(max_length=500)),
                ('projects', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
