# Generated by Django 2.0.5 on 2020-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_creator', '0002_auto_20200430_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='social_media',
            new_name='github',
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.TextField(default='sample', max_length=500),
            preserve_default=False,
        ),
    ]
