# Generated by Django 2.0.5 on 2020-05-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_creator', '0003_auto_20200501_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='GBPEC', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
