# Generated by Django 2.0.5 on 2020-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_creator', '0008_auto_20200502_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='projects',
            new_name='projectsSummary',
        ),
        migrations.AddField(
            model_name='user',
            name='projectsLink',
            field=models.TextField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='projectsTitles',
            field=models.TextField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='sample', max_length=50, primary_key=True, serialize=False),
        ),
    ]
